import {writeFile} from 'node:fs/promises';
import path from 'node:path';
const origin='https://nmit-solutions.com';
const xml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export function sitemapBody(pages){return `<section class="page-heading wrap"><div class="breadcrumb"><a href="/">Home</a><span>/</span><span>Sitemap</span></div><h1>Find your next connection.</h1><p>Browse NMIT services, engineering guides, company information, and website policies.</p></section><section class="wrap legal"><h2>Pages on this website</h2><ul>${pages.map(p=>`<li><a href="${p.route}">${xml(p.title)}</a></li>`).join('')}</ul><h2>Machine-readable files</h2><p><a href="/sitemap.xml">XML sitemap</a> · <a href="/robots.txt">Crawler rules</a> · <a href="/llms.txt">AI-readable website guide</a></p></section>`;}
export async function writeDiscovery(root,pages,posts){
 const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n${pages.map(p=>{const post=posts.find(post=>p.route===`/blog/${post.slug}/`);return `  <url><loc>${origin}${xml(p.route)}</loc>${post?`<lastmod>${post.modifiedAt||post.publishedAt}</lastmod><image:image><image:loc>${origin}${xml(post.featuredImage.replace('-768.webp','.png'))}</image:loc></image:image>`:''}</url>`;}).join('\n')}\n</urlset>\n`;
 await writeFile(path.join(root,'sitemap.xml'),sitemap);
 await writeFile(path.join(root,'robots.txt'),`# Public website content is available to crawlers.\nUser-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`);
 const group=(title,filter)=>`## ${title}\n\n${pages.filter(filter).map(p=>`- [${p.title}](${origin}${p.route}): ${p.description}`).join('\n')}\n`;
 const llms=`# NMIT Solutions\n\n> Bengaluru-based technology services covering cloud infrastructure, API and application integration, DevOps, and technology staffing.\n\nThe site introduces NMIT services and publishes engineering guides. Confirm project scope, availability, fees, and support commitments directly with NMIT. Worked examples in the guides are hypothetical where stated. Nodi is a fictional brand mascot; conceptual illustrations do not represent actual customer deployments.\n\nContact: info@nmit-solutions.com; +91 98869 70483. The contact form prepares an email locally; it does not submit an enquiry automatically.\n\n${group('Company and contact',p=>['/','/about/','/clients/','/contact/','/careers/'].includes(p.route))}\n${group('Services and workshop',p=>p.route.startsWith('/services/')||p.route==='/workshop/')}\n${group('Engineering guides',p=>p.route.startsWith('/blog/'))}\n${group('Website policies',p=>['/privacy/','/terms/','/cookies/','/accessibility/','/disclaimer/'].includes(p.route))}\n## Site navigation\n\n- [Sitemap](${origin}/sitemap/): Browse all website pages.\n- [XML sitemap](${origin}/sitemap.xml): Canonical page URLs for crawlers.\n`;
 await writeFile(path.join(root,'llms.txt'),llms);
}
