// A physical assembly of NMIT's service areas, rendered with native CSS 3D.
export function hero(mark) {
  const modules = [
    ['apps', 'Applications', 'API integration', '{ }'],
    ['cloud', 'Cloud', 'Infrastructure', '≋'],
    ['delivery', 'Delivery', 'DevOps', '↗'],
    ['people', 'People', 'Technology staffing', '◎']
  ];
  const explanations = {
    apps: ['APIs connect the applications and data you rely on.', 'Map the systems that need to exchange information, from existing applications to new cloud services.', 'api-integration', 'Discuss application integration'],
    cloud: ['Cloud infrastructure gives those applications a foundation.', 'Plan around your workloads, security, performance, and the support needed to keep systems running.', 'cloud-services', 'Explore cloud services'],
    delivery: ['DevOps brings development and operations into the same plan.', 'Review how changes move from development to deployment, together with the environments and teams behind each release.', 'devops', 'Explore DevOps delivery'],
    people: ['Technology staffing connects the work with the right skills.', 'Define the roles, responsibilities, and experience your project needs, alongside your existing team.', 'staffing', 'Discuss technology staffing']
  };
  const block = (key, name, caption, symbol) => {
    const hub = key === 'hub';
    const top = hub ? 'div' : 'button';
    return `<div class="assembly-block block-${key}" data-module="${key}"><${top} class="block-face face-top"${hub ? '' : ` type="button" data-open-system="${key}" aria-label="Explain ${name}" aria-expanded="false" aria-controls="explainer-${key}"`}><span class="assembly-symbol" aria-hidden="true">${symbol}</span><strong>${name}</strong><small>${caption}</small></${top}><div class="block-face face-front"></div><div class="block-face face-right"></div><div class="block-face face-back"></div><div class="block-face face-left"></div></div>`;
  };
  const boards = modules.map(([key, name, caption], i) => {
    const [summary, detail, slug, action] = explanations[key];
    return `<section class="explainer-board" id="explainer-${key}" data-explainer="${key}" tabindex="-1" aria-labelledby="explainer-title-${key}" hidden><div class="explainer-front"><div class="explainer-heading"><span class="mono">0${i + 1} / ${caption}</span><button type="button" class="explainer-close" aria-label="Close ${name} explanation">×</button></div><h2 id="explainer-title-${key}">${name}</h2><p class="explainer-summary">${summary}</p><p>${detail}</p><a class="text-link" href="/services/${slug}/">${action}</a></div></section>`;
  }).join('');
  return `<section class="hero wrap"><div class="hero-copy"><p class="hero-context"><span class="context-line"></span>Technology services from Bengaluru</p><h1><span class="sr-only">Build a more connected business.</span><span class="hero-title" aria-hidden="true"><span class="headline-mask"><span class="headline-line">Build a more</span></span><span class="headline-mask"><span class="headline-line headline-accent">connected</span></span><span class="headline-mask"><span class="headline-line">business.</span></span></span></h1><p class="hero-description">Cloud infrastructure, connected applications, and the people who make them work. We bring the pieces together.</p><div class="hero-actions"><a class="button" href="/contact/">Discuss your project</a><a class="text-link" href="/services/">Explore our services</a></div><p class="hero-footnote">Cloud / Integration / DevOps / People</p></div><div class="assembly" data-hero-model><div class="assembly-heading"><span>Four services, working together.</span><button class="motion-toggle" type="button" aria-pressed="false">Pause motion</button></div><div class="assembly-viewport" tabindex="0" role="group" aria-label="Interactive 3D model of NMIT’s connected services. Drag or use arrow keys to rotate." aria-describedby="assembly-instructions"><div class="assembly-scene"><div class="assembly-board"><svg class="assembly-routes" viewBox="0 0 400 400" fill="none" aria-hidden="true"><path class="board-grid" d="M0 80h400M0 160h400M0 240h400M0 320h400M80 0v400M160 0v400M240 0v400M320 0v400"/><path class="assembly-route route-apps" d="M87 88h60v112h53"/><path class="assembly-route route-cloud" d="M307 90v65H200v45"/><path class="assembly-route route-delivery" d="M314 306h-58V200h-56"/><path class="assembly-route route-people" d="M82 306v-51h118v-55"/><circle cx="200" cy="200" r="60" class="assembly-ring"/></svg><span class="board-registration registration-one">+</span><span class="board-registration registration-two">+</span>${modules.map(m => block(...m)).join('')}${block('hub', 'NMIT', 'Making the connection', mark)}</div></div></div><div class="assembly-toolbar"><span id="assembly-instructions">Select a service · Drag to adjust the view</span><button class="model-reset" type="button">Reset view</button></div><div class="assembly-selector" role="group" aria-label="Explore NMIT services">${modules.map(([key, name], i) => `<button type="button" data-system="${key}" aria-pressed="false" aria-expanded="false" aria-controls="explainer-${key}"><span class="mono">0${i + 1}</span>${name}</button>`).join('')}</div><p class="assembly-hint">Select a service to open its explanation board.</p><div class="assembly-explainers" aria-live="polite">${boards}</div></div></section>`;
}
