import { posts, nodi } from './blog.mjs';

export const homeFaqs = [
 ['What does NMIT Solutions help businesses with?', 'NMIT Solutions brings together cloud infrastructure, API and application integration, DevOps, and technology staffing. Start with a specific workflow, infrastructure constraint, delivery problem, or skill requirement so the conversation has a clear scope.'],
 ['Can we connect our ERP, CRM, and existing applications without replacing everything?', 'An integration project can retain useful existing systems while introducing defined interfaces between them. Begin by checking supported interfaces, record identity, data ownership, and error handling. Replacement becomes a separate decision where an existing system cannot meet essential requirements.'],
 ['What should we prepare for an API integration discussion?', 'Bring a list of the systems involved, one example business workflow, the data that must move, and the team responsible for each system. Include expected volumes, access constraints, known failures, and what a successful outcome should look like.'],
 ['What affects the cost and timeline of an integration project?', 'Scope depends on interface availability, data quality, mapping rules, security requirements, test environments, recovery behavior, and production support. A quote should state assumptions, exclusions, acceptance criteria, and operating responsibilities. NMIT confirms estimates after discussing your requirements.'],
 ['What happens in the free integration workshop?', 'The one-day onsite workshop reviews your current applications and business objectives, explores modern integration approaches, and identifies opportunities to improve. Contact NMIT to confirm location and availability. Delivery scope and commercial terms are discussed separately.'],
 ['Can cloud planning and DevOps be discussed together?', 'Yes. Deployment workflows depend on the infrastructure, identity controls, environments, and application connections behind them. Discussing these together helps identify dependencies before planning a migration or changing the release process.'],
 ['How do we discuss technology staffing?', 'Describe the role, responsibilities, technical skills, project context, and timing you need. NMIT can discuss team fit and engagement requirements alongside your cloud, integration, or delivery plans. Availability and terms are confirmed directly.'],
 ['Where is NMIT based, and how do we start?', 'NMIT is based in Pai Layout, Bengaluru, India. Use the contact page to prepare an email, call +91 98869 70483, or email info@nmit-solutions.com. Start with your business objective and the systems or people involved.']
];

export function homeJournal() {
 const featured=posts.find(p=>p.slug==='api-vs-event-driven-vs-batch-integration');
 const picks=['partner-payment-apis','hybrid-cloud-migration-checklist','api-integration-project-cost'].map(slug=>posts.find(p=>p.slug===slug));
 return `<section class="home-journal wrap" aria-labelledby="journal-title"><div class="journal-heading"><div><p class="section-label">The NMIT reading room</p><h2 id="journal-title">Understand the connection.<br>Then make the decision.</h2></div><a class="text-link" href="/blog/">Explore all 10 guides</a></div><div class="journal-layout"><article class="journal-feature"><a href="/blog/${featured.slug}/" class="journal-image"><img src="${featured.featuredImage}" alt="Nodi compares API requests, event distribution, and batch transfers in an NMIT integration architecture illustration" width="1536" height="1024" loading="lazy"></a><div class="journal-feature-copy"><span class="mono">Featured / Architecture</span><h3><a href="/blog/${featured.slug}/">One workflow.<br>Three ways to connect.</a></h3><p>${featured.excerpt}</p><a class="text-link" href="/blog/${featured.slug}/">Read the integration comparison</a></div></article><div class="journal-reading"><div class="reading-intro"><span class="mono">For your next project</span>${nodi('investigate')}</div>${picks.map((p,i)=>`<article class="journal-pick"><span class="mono">0${i+1}</span><div><p class="article-category">${p.articleSection}</p><h3><a href="/blog/${p.slug}/">${p.title}</a></h3></div><a href="/blog/${p.slug}/" tabindex="-1" aria-hidden="true"><img src="${p.featuredImage}" alt="NMIT mascot illustration for ${p.title}" width="1536" height="1024" loading="lazy"></a></article>`).join('')}<p class="journal-footnote">Practical guides. Worked examples. Questions worth asking before delivery.</p></div></div><nav class="journal-topics" aria-label="Browse engineering topics"><span class="mono">Follow a question</span><a href="/blog/legacy-system-integration/">Keep the legacy system?</a><a href="/blog/erp-crm-integration/">Who owns the data?</a><a href="/blog/api-integration-monitoring/">Did the workflow finish?</a><a href="/blog/integration-handover-checklist/">Who runs it next?</a></nav></section>`;
}

export function homeContext() {
 return `<section class="wrap home-context" aria-labelledby="connection-title"><div class="context-intro"><p class="section-label">Start with the business flow</p><h2 id="connection-title">A connected system needs<br>more than a working API.</h2><p>An order can be accepted while fulfilment is still pending. A CRM update can reach an ERP with the wrong record identity. A cloud migration can succeed while a partner connection stops working.</p><p>Bring the complete workflow into view: the applications, the data, the handoffs, and the people who handle exceptions.</p><a class="text-link" href="/services/api-integration/">Discuss application integration</a></div><div class="context-workflow"><div class="context-mascot" data-nodi-scene>${nodi('investigate')}<span class="mono">Follow the whole workflow</span></div><ol><li><strong>Map what moves</strong><p>Identify the source, destination, record owner, and business outcome for one flow.</p></li><li><strong>Make failure visible</strong><p>Define how delayed requests, duplicate events, and mismatched records are investigated.</p></li><li><strong>Plan who operates it</strong><p>Agree on monitoring, recovery, access, and handover before production responsibility changes.</p></li></ol></div></section>`;
}

export function homeQuestions() {
 return `<section class="wrap home-faq" aria-labelledby="faq-title"><div class="faq-intro"><p class="section-label">Before we talk</p><h2 id="faq-title">Questions about<br>working with NMIT.</h2><p>Choose the question closest to your project.</p><div class="faq-host" data-nodi-scene>${nodi('listen')}</div><a class="text-link" href="/contact/">Ask about your requirements</a></div><div class="faq-questions">${homeFaqs.map(([q,a],i)=>`<details data-nodi-answer><summary><span class="mono">${String(i+1).padStart(2,'0')}</span><h3>${q}</h3><span class="faq-toggle" aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>`;
}
