export const legalPages=[
 {slug:'cookies',title:'Cookies & browser storage',description:'How NMIT uses local browser storage, fonts, and external services.',sections:[
  ['What this website stores','This site uses a browser local-storage entry named nmit-theme to remember your light or dark appearance choice. Its value is light or dark. It remains on your device until you clear site data or your browser removes it. It does not contain your name, email address, or project details.'],
  ['Cookies and tracking','The website application does not set advertising or analytics cookies and does not include advertising or analytics scripts. Hosting infrastructure may process ordinary request information to deliver and protect the website. This notice does not describe cookies on external sites you choose to visit.'],
  ['Your choices','You can change the theme using the appearance button in the header. To remove the saved preference, clear this website’s site data in your browser settings. The website continues to work without the preference; it follows your device appearance setting.'],
  ['Fonts and outbound links','The site requests fonts from Google Fonts. Links to Google Maps, LinkedIn, and technical reference sites open those providers’ services. Their own privacy notices apply to your use of those services.'],
  ['Enquiry drafts','Contact form values are used to prepare an email draft on your device. The website application does not send these values to a server or save them in local storage. You choose whether to send the email using your email application.']
 ]},
 {slug:'accessibility',title:'Accessibility statement',description:'Accessibility features, known limits, and how to report a barrier on the NMIT website.',sections:[
  ['Using the website','The site includes a skip-to-content link, semantic headings, keyboard-operable navigation, labeled form fields, and text descriptions for meaningful images. Light and dark themes use contrast-tested text and button colors.'],
  ['Motion and interactive content','The homepage service model provides buttons as an alternative to dragging and includes a pause-motion control. The website respects your device’s reduced-motion preference. Article illustrations and written explanations remain available without interacting with the model.'],
  ['Reading and forms','Layouts adapt to smaller screens. Wide article tables can be scrolled within their own containers. The contact form prepares an email draft; if that does not work with your setup, you can email or call NMIT directly.'],
  ['Known limits','Automated and manual checks do not cover every combination of assistive technology and browser. Text embedded within illustrations may be harder to read at small sizes; image descriptions and surrounding article content provide the related explanation. This statement is not a claim of certified accessibility conformance.'],
  ['Report a barrier','Email info@nmit-solutions.com or call +91 98869 70483. Include the page address, what you were trying to do, the difficulty you encountered, and your browser or assistive technology if you are comfortable sharing it. You can also request the information through those contact channels.']
 ]},
 {slug:'disclaimer',title:'Content & illustration notice',description:'How to interpret NMIT engineering guides, examples, illustrations, and third-party references.',sections:[
  ['Engineering guides','Articles explain general architecture and operational concepts. Their examples do not assess your particular environment or replace project-specific requirements, security review, testing, or vendor documentation. Confirm assumptions against the systems you operate before applying an example.'],
  ['Examples and imagery','Worked examples identified as hypothetical are not customer case studies. Nodi is a fictional NMIT mascot. Mascot artwork and conceptual illustrations are AI-generated brand assets, not photographs of employees, actual product screenshots, or evidence of a delivered customer engagement.'],
  ['Names, logos, and references','Company names and third-party logos identify the organizations or tools being discussed. They remain the property of their respective owners. A reference or illustration does not by itself establish endorsement, certification, partnership, or a particular customer result.'],
  ['Commercial information','Service descriptions introduce topics for a direct conversation. Project scope, fees, availability, staffing, and support commitments are confirmed separately. Contact NMIT for current details rather than treating an article example as a quotation.'],
  ['Corrections','If you find an error, an outdated reference, or an issue with an image or attribution, email info@nmit-solutions.com with the page address and the specific issue.']
 ]}
];

export function legalBody(entry,nodi){return `<section class="page-heading wrap"><div class="breadcrumb"><a href="/">Home</a><span>/</span><span>Website information</span></div><h1>${entry.title}</h1><p>${entry.description}</p><p class="small">Last updated: 17 September 2026</p></section><article class="wrap legal">${entry.sections.map(([title,text],i)=>`<section><h2>${title}</h2>${i===1?`<span class="nodi-scene nodi-right" data-nodi-scene>${nodi(entry.slug==='accessibility'?'explain':'listen')}</span>`:''}<p>${text}</p></section>`).join('')}<p>Related information: <a href="/privacy/">Privacy notice</a> · <a href="/terms/">Website terms</a> · <a href="/contact/">Contact NMIT</a>.</p></article>`;}
